In [3]:
import torch

print(torch.__version__)

2.5.1


In [11]:
x = torch.tensor( [[2],[2]] )
print(x)
print(x.shape)
print(x.ndim)

tensor([[2],
        [2]])
torch.Size([2, 1])
2


In [10]:
x = torch.tensor(6)
x.item()

6

In [33]:
x = torch.tensor( [[1,2],[3,4]] , dtype=torch.float64 ,device="cuda",requires_grad=True)

print(x)
print(x.device)
print(x.dtype)

tensor([[1., 2.],
        [3., 4.]], device='cuda:0', dtype=torch.float64, requires_grad=True)
cuda:0
torch.float64


In [ ]:
### Random tensors

new = torch.rand(3,4)
new = torch.randn(3,4)
new = torch.zeros(3,4,2)
new = torch.ones(3,4,2)
print(new)

In [28]:
x = torch.zeros_like(new)
x = torch.arange(0,10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [43]:
### Operations

new = torch.tensor( [[1,2],[3,4]])
#print(new+10)
new2 = torch.tensor( [[5,6],[7,8]])
#print(new*new2)  ## element-wise multiplication
#print(torch.matmul(new,new2))

#print(torch.mean(new.type(torch.float32)))  ## Mean of all the elements
#print(new[0].max())
print(new[0].argmax())

tensor(1)


Reshaping , Stacking , Squeezing and Unsqueezing tensors

Reshaping changes the tensor to a defined shape.

View gives the tensor a certain shape but keeps same memory as original tensor.

Stacking combines multiple tensors.

Squeeze remove all 1 dimension from a tensor.

Unsqueeze adds  1 dimension to a tensor.

Premute gives a veiw of the tensor with dimensions swapped in a certain way.

In [ ]:

x = torch.tensor([0,1,23,4,6,87])
print(x.shape)
x = x.reshape(1,6)

z = x.view(6,1)  
z[3][0] = 5   ## Changing z changes x because they share same memory as we used view
print(x)



torch.Size([6])
tensor([[ 0,  1, 23,  5,  6, 87]])


In [24]:
x = torch.tensor([[1,2,4,5]])
y = torch.tensor([[3,4,5,6]])
z = torch.tensor([6,7,8,9])
stacked = torch.stack([x,y],dim=-1)

print(stacked)

tensor([[[1, 3],
         [2, 4],
         [4, 5],
         [5, 6]]])


In [ ]:
x  = torch.tensor([[1,2]])
print(x.shape) 
x = x.squeeze()  ## Cutting off the extra unsed dimension
print(x.shape)

torch.Size([1, 2])
torch.Size([2])


In [ ]:
x = torch.tensor([[1,2],[3,4]])
print(x.shape)
x = x.unsqueeze(dim=2) ## Adding a new valid positioned dimension
print(x)

torch.Size([2, 2])
tensor([[[1],
         [2]],

        [[3],
         [4]]])


In [47]:
#### Numpy to Pytorch conversion
import numpy as np

array = np.arange(1,8)
print(array)
pytorch_tensor = torch.from_numpy(array)
print(pytorch_tensor)
numpy_array = pytorch_tensor.numpy()
print(numpy_array)

[1 2 3 4 5 6 7]
tensor([1, 2, 3, 4, 5, 6, 7])
[1 2 3 4 5 6 7]


WE USE RANDOM SEED TO REPRODUCE THE SAME TENSORS

In [60]:
RANDOM_SEED = 50
torch.manual_seed(RANDOM_SEED)  ## Try commenting out this line
print(torch.randn(1,2))

tensor([[ 0.4625, -0.1692]])
